#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
//Files we are testing:
#include "includes/stub/stub.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

void basic_test(bool debug=false);

int main(int argv, char** argc)
{
  cout << "\n" << endl;

  basic_test();

  cout << "\n\n=====================" << endl;
  
  return 0;
}


void basic_test(bool debug)
{
  stub();
}